name: Markdown

on:
  pull_request:
    paths:
      - "**/*.md"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Markdown files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8
